import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SessionProvider from '@/components/SessionProvider';
import { getServerSession } from 'next-auth';
import './globals.css';
import NavBar from '@/components/NavBar/NavBar';
import { useRouter } from 'next/navigation';
import RedirectC from '@/components/Redirect/RedirectC';
import CheckAuth from '@/components/Auth/CheckAuth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'admin-console',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="bg-blue-800 max-w-full min-h-screen flex">
            <NavBar />
            <div className="bg-white rounded-md p-2 mt-2 mr-2 w-full">{children}</div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
